# Generated by Django 5.2 on 2025-04-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoescolar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestao',
            name='carga_horaria',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
