# Generated by Django 5.2 on 2025-05-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoescolar', '0005_alter_gestao_carga_horaria_alter_gestao_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestao',
            name='carga_horaria',
            field=models.CharField(),
        ),
    ]
