# Generated by Django 5.1.7 on 2025-05-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoescolar', '0006_alter_gestao_carga_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestao',
            name='carga_horaria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gestao',
            name='disciplina',
            field=models.CharField(max_length=100),
        ),
    ]
