# Generated by Django 5.2 on 2025-05-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoescolar', '0002_gestao_carga_horaria'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='disciplina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='gestaoescolar.gestao'),
            preserve_default=False,
        ),
    ]
