# Generated by Django 5.1.7 on 2025-05-06 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoescolar', '0007_alter_gestao_carga_horaria_alter_gestao_disciplina'),
        ('professor', '0006_alter_professor_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='gestaoescolar.gestao'),
        ),
    ]
