# Generated by Django 5.2 on 2025-05-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0007_alter_professor_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
